# Generated by Django 2.0 on 2019-09-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_geoip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='django_geoip.Region'),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geoip.City'),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_geoip.Country'),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='django_geoip.Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='django_geoip.Country'),
        ),
    ]
