# Generated by Django 2.0.9 on 2019-06-19 19:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190619_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
