# Generated by Django 2.2.2 on 2019-06-20 23:43

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
