# Generated by Django 2.0 on 2019-06-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190620_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Full-time'), (2, 'Half-time')], null=True, verbose_name='job_type'),
        ),
    ]
