# Generated by Django 2.1 on 2019-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20190709_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='device',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
