# Generated by Django 2.0 on 2019-07-11 22:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_post_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326),
        ),
    ]
