# Generated by Django 2.0 on 2019-07-11 22:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20190711_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city_hall',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
