# Generated by Django 2.0 on 2019-07-11 22:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_post_city_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city_hall',
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
