# Generated by Django 2.0 on 2019-06-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='post_id',
        ),
    ]
