# Generated by Django 2.0 on 2019-07-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image_pictures/%Y/%m/%d/', verbose_name='post image'),
        ),
    ]
