# Generated by Django 2.0 on 2019-06-21 16:01

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
