# Generated by Django 2.0 on 2019-07-12 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import martor.models
import places.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('job_type', models.IntegerField(blank=True, choices=[(1, 'Full-time'), (2, 'Half-time')], null=True, verbose_name='job_type')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('content', martor.models.MartorField()),
                ('draft', models.BooleanField(default=False)),
                ('location', places.fields.PlacesField(blank=True, max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('read_time', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('ip_region', models.CharField(blank=True, max_length=255)),
                ('ip_city', models.CharField(blank=True, max_length=255)),
                ('ip_code', models.CharField(blank=True, max_length=255)),
                ('device', models.CharField(blank=True, max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Category')),
                ('skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
