# Generated by Django 2.0 on 2019-07-12 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0002_userdashboardmodules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDashboardModules',
        ),
    ]
