# Generated by Django 2.0 on 2019-07-31 16:25

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
