# Generated by Django 2.0 on 2019-09-23 14:06

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20190731_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
