# Generated by Django 2.0.9 on 2019-06-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='a cover image', upload_to=userena.models.upload_to_cover, verbose_name='cover')),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('bn', 'Bengali'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('es-co', 'Colombian Spanish'), ('et', 'Estonian'), ('fa', 'Persian'), ('fr', 'French'), ('hi', 'Hindi'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('lt', 'Lithuanian'), ('mn', 'Mongolian'), ('nb', 'Norwegian'), ('nl', 'Dutch'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sw', 'Swahili'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', help_text='Default language.', max_length=5, verbose_name='language')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='gender')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('about_me', models.TextField(blank=True, verbose_name='about me')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_profile', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following_profile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'permissions': (('view_profiles', 'Can view profile'),),
                'abstract': False,
            },
        ),
    ]
